name: _hugo-deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      url:
        required: true
        type: string
      hostname:
        required: true
        type: string
      git-sha:
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    name: 'Hugo Build'
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash
        working-directory: web
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.145.0'
          extended: true

      - name: Cache Hugo modules
        uses: actions/cache@0400d5f644dc74513175e3cd8d07132dd4860809 # v4.2.4
        with:
          path: ${{ runner.temp }}/hugo_cache
          key: ${{ runner.os }}-hugomod-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-hugomod-

      # - name: CNAME file
      #   run: echo "$GH_DOMAIN" >> static/CNAME
      #   env:
      #     GH_DOMAIN: ${{ inputs.hostname }}

      - name: Build with Hugo
        run: |
          hugo \
            --gc \
            --minify \
            --enableGitInfo \
            --baseURL "$URL"
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          HUGO_ENVIRONMENT: production
          TZ: Europe/Stockholm
          URL: ${{ inputs.url }}
          HUGO_PARAMS_gitCommit: ${{ inputs.git-sha }}
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@56afc609e74202658d3ffba0e8f6dda462b719fa # v3.0.1
        with:
          path: web/public

  deploy:
    name: 'Hugo Deploy'
    runs-on: ubuntu-latest
    needs: build
    environment: 
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}
    permissions:
      pages: write
      id-token: write

    steps:
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main' && (github.event_name == 'push' || github.event_name == 'workflow_dispatch')
        id: deployment
        uses: actions/deploy-pages@d6db90164ac5ed86f2b6aed7e0febac5b3c0c03e # v4.0.5
