name: _terraform-deploy

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      url:
        required: true
        type: string
      hostname:
        required: true
        type: string
      git-sha:
        required: true
        type: string
    secrets:
      TF_STATE_TOKEN:
        required: true
      TF_GITHUB_TOKEN:
        required: true

permissions:
  contents: read

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment }}

    defaults:
      run:
        shell: bash
        working-directory: terraform
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@651471c36a6092792c552e8b1bef71e592b462d8 # v3.1.1

      - name: Terraform Init
        id: terraform_init
        run: |
          terraform init \
           -backend-config="password=$TF_STATE_TOKEN"
        env:
          TF_STATE_TOKEN: ${{ secrets.TF_STATE_TOKEN }}

      - name: Terraform Plan
        id: terraform_plan
        run: terraform plan -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}

      - name: Terraform Apply
        id: terraform_Apply
        if: (github.ref == 'refs/heads/main' && github.event_name == 'push') || (github.event_name == 'workflow_dispatch' && github.event.inputs.do-apply == 'true')
        run: terraform apply -auto-approve -input=false
        env:
          GITHUB_TOKEN: ${{ secrets.TF_GITHUB_TOKEN }}
