name: '🩺 HUGO - Continuous Integration (CI)'

on:
  pull_request:
    branches:
      - main
      # - staging
    paths: 
      - 'web/**'
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  hugo-ci:
    name: 'HUGO CI'
    runs-on: ubuntu-latest
  
    defaults:
      run:
        shell: bash
        working-directory: web
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@75d2e84710de30f6ff7268e08f310b60ef14033f # v3.0.0
        with:
          hugo-version: '0.144.2'
          extended: true

      - name: Hugo Audit
        run: |
          hugo && grep -inorE "<\!-- raw HTML omitted -->|ZgotmplZ|\[i18n\]|\(\)|(<nil>)|hahahugo" public/
        env:
          HUGO_CACHEDIR: ${{ runner.temp }}/hugo_cache
          TZ: Europe/Stockholm
          HUGO_MINIFY_TDEWOLFF_HTML_KEEPCOMMENTS: true
          HUGO_ENABLEMISSINGTRANSLATIONPLACEHOLDERS: true
