name: Event Trigger Example

on: 
  release:
    types: [published, released]

jobs:
  print-event:
    runs-on: ubuntu-latest
    steps:
      - name: Print the event that triggered the workflow
        run: |
          echo "Event name: ${{ github.event_name }}"
          echo "Full event data:"
          echo "${{ toJson(github.event) }}"

      - name: published
        if: github.event.release.action == 'published'
        run: echo "github.event.release.action == 'published'"

      - name: released
        if: github.event.release.action == 'released'
        run: echo "github.event.release.action == 'released'"
        
      - name: released action
        if: github.event.action == 'released'
        run: echo "github.event.action == 'released'"

      - name: released action
        if: github.event.action == 'released'
        run: echo "github.event.action == 'released'"
