name: tfsec

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  actions: read
  contents: read
  security-events: write

jobs:
  tfsec:
    name: tfsec sarif report
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: tfsec
        uses: aquasecurity/tfsec-sarif-action@21ded20e8ca120cd9d3d6ab04ef746477542a608 # v0.1.4
        with:
          sarif_file: tfsec.sarif
          working_directory: terraform
          tfsec_args: --ignore-hcl-errors

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@1bb15d06a6fbb5d9d9ffd228746bf8ee208caec8 # v2.20.5
        with:
          sarif_file: tfsec.sarif
